[repository]
REGISTRY_NAME = "nathan-vm"

REPOSITORY_NAME = "web-browser-scrapper-piece"
REPOSITORY_LABEL = "web-browser-scrapper-piece"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "1.0.0"
