FROM ghcr.io/tauffer-consulting/domino-base-piece:latest
# Install specific requirements to run OpenCV
RUN apt-get update; apt-get clean
RUN apt-get install -y wget

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install ./google-chrome-stable_current_amd64.deb -y --fix-missing
RUN rm -rf ./google-chrome-stable_current_amd64.deb

# Install specific dependencies in domino_env virtual environment
RUN pip install --no-cache-dir selenium==4.19.0